config/routes.rb
Rails.application.routes.draw do
resources :products do
  collection do
    get 'search'
  end
end
resources :orders do
  resources :payments, only: [:new, :create, :index, :destroy]
  resources :order_transactions, only: [:destroy], controller: 'order_transactions'
end
resources :order_items, only: [:show, :create, :new, :index, :update, :destroy]
resources :cards, only: [:show]
resources :products do
  resources :comments, only: [:create, :update, :destroy, :edit]
end
post '/check_promo_code', to: 'order_items#check_promo_code'
get 'profile' => 'users#show'
devise_for :users
root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :content, presence: true
  validate :user_cannot_comment_on_own_product
  def user_cannot_comment_on_own_product
    errors.add(:user, "can't comment on own product") if user_id == product&.user_id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_product
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :check_comment_on_own_product, only: [:create]
  def create
    @comment = @product.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @product, notice: 'Comment was successfully created.'
    else
      render 'products/show'
    end
  end
  def edit
    @comment
  end
  def update
    if @comment.update(comment_params)
      redirect_to @product, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end
  def destroy
    @comment.destroy
    redirect_to @product, notice: 'Comment was successfully deleted.'
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end
  def set_comment
    @comment = Comment.find(params[:id])
  end
  def check_comment_on_own_product
    redirect_to @product, notice: 'You cannot comment on your own product.' if current_user.id == @product.user_id
  end
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.user.name %>:</strong>
  <%= comment.content %>
</p>
<% if current_user && current_user.id == comment.user_id %>
  <p>
    <%= link_to 'Edit', edit_product_comment_path(comment.product, comment) %>
    <%= link_to 'Delete', [comment.product, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@product, @comment], remote: true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.text_area :content, placeholder: 'Add a comment...' %>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<div class="container mtop">
  <h1>Edit Comment</h1>
  <%= render 'form' %>
  <%= link_to 'Back', @comment.product %>
</div>