config/routes.rb
Rails.application.routes.draw do
resources :products do
  collection do
    get 'search'
  end
end
resources :orders do
  resources :payments, only: [:new, :create, :index, :destroy]
  resources :order_transactions, only: [:destroy], controller: 'order_transactions'
end
resources :order_items, only: [:show, :create, :new, :index, :update, :destroy]
resources :cards, only: [:show]
resources :products do
  resources :comments, only: [:create, :update, :destroy, :edit]
end
post '/check_promo_code', to: 'order_items#check_promo_code'
get 'profile' => 'users#show'
devise_for :users
root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :content, presence: true
  validate :user_cannot_comment_on_own_product
  def user_cannot_comment_on_own_product
    errors.add(:user, "can't comment on own product") if user_id == product&.user_id
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
  mount_uploader :image, ImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :user
  has_many :payments
  has_many :products, through: :order_items
  scope :in_progress, -> { where(status: 'in_progress') }
  before_save :set_subtotal

  def update_subtotal
    self.subtotal = calculate_subtotal
    save
  end
  def calculate_subtotal
    order_items.sum(&:total)
  end

  private

  def set_subtotal
    self.subtotal = calculate_subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validate :product_belongs_to_other_user
  before_save :set_unit_price_and_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end
  def total
    quantity * product.price
  end

  private

  def product_belongs_to_other_user
    if product.user == order.user
      errors.add(:base, "You cannot add your own products to your cart")
    end
  end
  def set_unit_price_and_total
    self[:unit_price] = unit_price
    self[:total] = total
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :comments, dependent: :destroy
# ========================product image uploader==============
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
# ===========================serial number=============
  before_create :generate_serial_number

  private

  def generate_serial_number
    self.serial_number = generate_unique_serial_number
  end
  def generate_unique_serial_number
    loop do
      serial_number = SecureRandom.hex(4).upcase # You can customize this as needed
      break serial_number unless Product.exists?(serial_number: serial_number)
    end
  end
end

app/models/promo_code.rb
class PromoCode < ApplicationRecord
    validates :code, presence: true, uniqueness: true, format: { with: /\A[A-Z0-9]+\z/ }, length: { in: 4..10 }
  validates :discount, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }
  validates :valid_til, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :products
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, FileUploader
  validates :name, presence: true, uniqueness: true
  validates :phone_number, presence: true, format: { with: /\A\d{11}\z/, message: "must be 11 digits" }
  validates_uniqueness_of :phone_number
  attr_accessor :phone
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @order_items = current_order.order_items
    @order = current_order
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @images = Image.all
    @product = Product.find_by(id: params[:product_id])
    @order_item = OrderItem.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if user_signed_in?
      current_user.orders.in_progress.first_or_create
      elsif !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      order = Order.create
      session[:order_id] = order.id
      order
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerece</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'promo' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script>
    document.addEventListener('DOMContentLoaded', function () {
      setupStripe();
    });
    function setupStripe() {
    }
    </script>
  </head>
  <body>
    <%= render "shared/navbar"%>
    <div class="row">
      <%= yield %>
    </div>
    <%= render "shared/footer"%>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_Slider.html.erb
<div id="carouselExampleCaptions" class="mtop shadow-lg carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner slidcol">
    <div class=" carousel-item active">
      <div class="slidimg">
        <%= image_tag 'slider/t1.png',class: " img-fluid ", width: '30%', height: '50%'%>
       </div>
      <div class="slidtext carousel-caption d-none d-md-block">
        <h2>welcome to our shop</h2>
        <p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road.</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="slidimg">
        <%= image_tag 'slider/t2.png',class: "d-block img-fluid ", width: '30%', height: '50%'%>
      </div>
      <div class="slidtext carousel-caption d-none d-md-block">
        <h2>Revolution</h2>
        <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly..</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="slidimg">
        <%= image_tag 'slider/s1.png',class: "d-block img-fluid ", width: '30%', height: '50%'%>
      </div>
      <div class="slidtext carousel-caption d-none d-md-block">
        <h2>Quality Control</h2>
        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_featuredproduct.html.erb
<div class=" banner shadow-lg ">
  <h4 class="newpr">FEATURED PRODUCTS</h4>
</div>

app/views/shared/_footer.html.erb
<div class="banner shadow-lg">
  <h4 class="newprr">Aone Tech.Solutions</h4>
  <ul class="navbar-nav  footernav">
    <li class="nav-item">
      <%= link_to "Home", root_path, class: "nav-link active color" %>
    </li>
    <li class="nav-item">
      <%= link_to "New Product", new_product_path, class: "nav-link color" %>
    </li>
    <li class="nav-item">
      <a class="nav-link color" href="#">Contact_us</a>
    </li>
    <li class="nav-item">
      <a class="nav-link color" href="#">About_us</a>
    </li>
  </ul>
  <div class="footericone">
    <a href="https://www.linkedin.com/company/aonetech/" target="_blank" rel="noopener noreferrer">
      <i class="bi bi-linkedin linkd"></i>
    </a>
    <a href="https://www.youtube.com/" target="_blank" rel="noopener noreferrer">
      <i class="bi bi-youtube yout"></i>
    </a>
  </div>
  <p class="allri">© 2023 Aone Tech.Solutions. All rights reserved by <span class="adcolo">Adnan Naeem</span></p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navcol shadow-lg fixed-top">
  <div class="container-fluid">
    <%= image_tag 'navbar/shop.png', class: "img-fluid logo", width: '7%', height: '5%' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Product", new_product_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact_us</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="#">About_us</a>
        </li>
      </ul>
      <form class="fp d-flex" action="<%= search_products_path %>" method="get">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <div id="card-i">
        <% if current_order.present? && current_order.order_items.any? %>
        <%= link_to card_path(current_order.id) do %>
        <span class="bi bi-cart-plus-fill caricone"></span>
        <span class="cartsize"><%= current_order.order_items.size %></span>
        <% end %>
        <% end %>
      </div>
      <div class="justify-content-end align-items-center">
        <div class="group d-flex flex-column justify-content-end align-items-center">
          <% if user_signed_in? %>
            <% if current_user %>
              <img class="img-fluid profile" src="<%= current_user.image_url %>">
            <% end %>
            <strong><%= link_to current_user.name, profile_path, class: "linktitle" %></strong>
            <% else %>
            <%= link_to " Sign In", new_user_session_path, style: 'color:white; background-color:black; padding:6px; margin-bottom:1rem;', :class => 'navbar-brand  buttons' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>