config/routes.rb
Rails.application.routes.draw do
resources :products do
  collection do
    get 'search'
  end
end
resources :orders do
  resources :payments, only: [:new, :create, :index, :destroy]
  resources :order_transactions, only: [:destroy], controller: 'order_transactions'
end
resources :order_items, only: [:show, :create, :new, :index, :update, :destroy]
resources :cards, only: [:show]
resources :products do
  resources :comments, only: [:create, :update, :destroy, :edit]
end
post '/check_promo_code', to: 'order_items#check_promo_code'
get 'profile' => 'users#show'
devise_for :users
root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :content, presence: true
  validate :user_cannot_comment_on_own_product
  def user_cannot_comment_on_own_product
    errors.add(:user, "can't comment on own product") if user_id == product&.user_id
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
  mount_uploader :image, ImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :user
  has_many :payments
  has_many :products, through: :order_items
  scope :in_progress, -> { where(status: 'in_progress') }
  before_save :set_subtotal

  def update_subtotal
    self.subtotal = calculate_subtotal
    save
  end
  def calculate_subtotal
    order_items.sum(&:total)
  end

  private

  def set_subtotal
    self.subtotal = calculate_subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validate :product_belongs_to_other_user
  before_save :set_unit_price_and_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end
  def total
    quantity * product.price
  end

  private

  def product_belongs_to_other_user
    if product.user == order.user
      errors.add(:base, "You cannot add your own products to your cart")
    end
  end
  def set_unit_price_and_total
    self[:unit_price] = unit_price
    self[:total] = total
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :comments, dependent: :destroy
# ========================product image uploader==============
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
# ===========================serial number=============
  before_create :generate_serial_number

  private

  def generate_serial_number
    self.serial_number = generate_unique_serial_number
  end
  def generate_unique_serial_number
    loop do
      serial_number = SecureRandom.hex(4).upcase # You can customize this as needed
      break serial_number unless Product.exists?(serial_number: serial_number)
    end
  end
end

app/models/promo_code.rb
class PromoCode < ApplicationRecord
    validates :code, presence: true, uniqueness: true, format: { with: /\A[A-Z0-9]+\z/ }, length: { in: 4..10 }
  validates :discount, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }
  validates :valid_til, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :products
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, FileUploader
  validates :name, presence: true, uniqueness: true
  validates :phone_number, presence: true, format: { with: /\A\d{11}\z/, message: "must be 11 digits" }
  validates_uniqueness_of :phone_number
  attr_accessor :phone
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @order_items = current_order.order_items
    @order = current_order
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_product
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :check_comment_on_own_product, only: [:create]
  def create
    @comment = @product.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @product, notice: 'Comment was successfully created.'
    else
      render 'products/show'
    end
  end
  def edit
    @comment
  end
  def update
    if @comment.update(comment_params)
      redirect_to @product, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end
  def destroy
    @comment.destroy
    redirect_to @product, notice: 'Comment was successfully deleted.'
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end
  def set_comment
    @comment = Comment.find(params[:id])
  end
  def check_comment_on_own_product
    redirect_to @product, notice: 'You cannot comment on your own product.' if current_user.id == @product.user_id
  end
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @images = Image.all
    @product = Product.find_by(id: params[:product_id])
    @order_item = OrderItem.new
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  def index
    @orders = current_user.orders.includes(order_items: :product)
    @order = current_user.orders.last
  end
  def new
    @order = current_user.orders.find(params[:order_id])
  end
  def create
    @order = current_user.orders.find(params[:order_id])
    @order.update_subtotal
    if session[:discount].present?
      @order.subtotal *= (1 - session[:discount])
      session[:discount] = nil # Clear the discount from the session
    end
    charge = create_stripe_charge(@order.subtotal, params[:stripeToken])
    @order.order_items.each do |order_item|
    create_transaction(charge, order_item)
    end
    @order.update(status: 'paid')
    flash[:success] = 'Payment was successful!'
    redirect_to order_payments_path(order_id: @order)
    rescue Stripe::CardError => e
    flash[:error] = e.message
    render :new
  end

  private

  def create_stripe_charge(amount, stripe_token)
    Stripe.api_key = 'sk_test_51OHilMC6RwpJpsY7rgdWVJSESd48tGWOvE9yj6jBdtvfJpjY0EutV0R5yy1fikcFmjxFbD9dd3kmvTnzvdSBRhWA00U9Oj9Eve'
    charge = Stripe::Charge.create(
      amount: (amount * 100).to_i,
      currency: 'usd',
      source: stripe_token,
      description: 'Order payment for a test Rails application'
    )
    @order.update(status: 'paid')
    charge
  end
  def create_transaction(charge, order_item)
    Transaction.create!(
      order: @order,
      title: order_item.product.title,
      price: order_item.product.price,
      quantity: order_item.quantity
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if user_signed_in?
      current_user.orders.in_progress.first_or_create
      elsif !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      order = Order.create
      session[:order_id] = order.id
      order
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_card.html.erb
<div class="cartd">
  <%= link_to card_path(current_order.id) do %>
    <span class="bi bi-cart-plus-fill caricone"></span>
    <span class="cartsize"><%= current_order.order_items.size %></span>
  <% end %>
</div>

app/views/cards/_cards_item.html.erb
<div class="container mtop">
  <div id="order-items-list">
    <div class="d-flex justify-content-between">
      <h1>WishList</h1>
      <h5><%= link_to "Go Back Home", root_path, class: "nav-link backhome" %></h5>
    </div>
    <div class="d-flex justify-content-between">
      <div class="row">
        <% @order_items.each do |item| %>
          <div class="card mb-5 col-lg-11 col-md-11 col-sm-12 cardbg">
            <div class="row g-0">
              <div class="col-md-4 itemcarddd">
                <% image = item.product.images.first %>
                <% if image.present? %>
                  <%= image_tag(image.image.url, class: 'cardpic') %>
                <% else %>
                  <p>No image available</p>
                <% end %>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title"><%= item.product.title %></h5>
                  <p><%= item.product.price %></p>
                </div>
                <div class="card-body justify-content-between">
                  <%= form_for item, remote: true do |f| %>
                    <%= f.hidden_field :product_id, value: item.product.id %>
                    <%= f.number_field :quantity, value: item.quantity.to_i, class: 'quantity-input quantitfield' %>
                    <%= f.submit "Update Cart", class: 'hidden-update-btn', style: 'display: none;' %>
                    <%= link_to 'Delete', order_item_path(item.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'delete-link Deletebtn' %>
                  <% end %>
                  <br>
                  <h3>total: <span class="subtotal" data-price="<%= item.product.price %>"><%= item.total %></span>$</h3>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-12">
        <div class="card cardbg">
           <h3 class="justify-content-center align-middle text-center mt-2">SubTotal: <span class="total-value "><%= current_order.subtotal %></span>$</h3>
          <%= image_tag 'Payment/f55.png', class: "img-fluid payment " %>
          <form class="coupnh" id="promoForm">
            <label  for="promoCode">Enter Promo Code</label>
            <div class="coupns">
            <input class="coupni" type="text" id="promoCode" name="promoCode">
            <button class="coupnb" type="button" onclick="checkPromoCode()">Apply Promo</button>
          </div>
          <div id="discountResult"></div>
          </form>
          <%= render 'payments/new', order_id: @order.id %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
$(document).ready(function() {
  function handleQuantityChange() {
    var quantity = $(this).val();
    var price = parseFloat($(this).closest('.card-body').find('.subtotal').data('price'));
    var subtotal = (quantity * price).toFixed(2);
    $(this).closest('.card-body').find('.subtotal').text(subtotal);
    $(this).closest('form').find('.hidden-update-btn').click();
    updateUI();
  }
  function updateUI() {
    var total = 0;
    $('.subtotal').each(function() {
      total += parseFloat($(this).text());
    });
    var discountResult = $('#discountResult');
    var discountValue = parseFloat(discountResult.data('discount'));
    if (!isNaN(discountValue) && discountValue > 0) {
      total *= (1 - discountValue);
      discountResult.text('Discount Applied: ' + (discountValue * 100) + '%');
    } else {
      discountResult.text('');
    }

    $('.total-value').text(total.toFixed(2));
  }

  $('.quantity-input').on('input', handleQuantityChange);
  $('.delete-link').on('ajax:complete', function(event, xhr, status) {
    if (status === 'success') {
      updateUI();
    }
  });
  function updateDiscountResult(discountValue) {
    var discountResult = $('#discountResult');
    if (!isNaN(discountValue) && discountValue > 0) {
      discountResult.text('Discount Applied: ' + (discountValue * 100) + '%');
    } else {
      discountResult.text('');
    }
  }
  // Function to check promo code
  function checkPromoCode() {
    const promoCode = $('#promoCode').val();
    console.log("Checking Promo Code:", promoCode);
    fetch('/check_promo_code', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content
      },
      body: JSON.stringify({ promoCode: promoCode })
    })
      .then(response => response.json())
      .then(data => {
        console.log("Response Data:", data);
        $('#discountResult').data('discount', data.discount);
        updateDiscountResult(data.discount);
        updateUI();
      })
      .catch(error => {
        console.error('Error:', error);
      });
  }
  $('#promoForm button').on('click', checkPromoCode);
});


</script>

app/views/cards/show.html.erb
<div id="card-item">
  <%= render 'cards_item'%>
</div>

app/views/home/index.html.erb
<%= render "shared/Slider"%>
<%= render "shared/featuredproduct"%>
<%= render "products/card"%>

app/views/payments/_new.html.erb
<div class="container">
  <%= form_tag order_payments_path(@order), id: 'payment-form' do %>
    <div class="form-row">
      <label for="card-element" class="m-1">
        Credit or debit card
      </label>
      <div id="card-element" >
      </div>
      <div id="card-errors" role="alert"></div>
    </div>
    <%= hidden_field_tag 'user_name', current_user.name %>
    <%= hidden_field_tag 'user_email', current_user.email %>
    <button class="paymentbutton " type="submit">Check Out Payment</button>
  <% end %>
</div>

<script src="https://js.stripe.com/v3/"></script>
<script>
document.addEventListener('turbolinks:load', function () {
  setupStripe();
});
function setupStripe() {
  var stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
  var elements = stripe.elements();
  var form = document.getElementById('payment-form');
  var paymentButton = form.querySelector('.paymentbutton');
  var card = elements.create('card');
  card.mount('#card-element');
  card.addEventListener('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });
  form.addEventListener('submit', function(event) {
    event.preventDefault();
    paymentButton.disabled = true;
    var additionalData = {
      name: document.getElementById('user_name').value,
      email: document.getElementById('user_email').value
    };

    stripe.createToken(card, additionalData).then(function(result) {
      if (result.error) {
        // Inform the user if there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server.
        stripeTokenHandler(result.token);
      }
    });
  });

  function stripeTokenHandler(token) {
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);
    form.submit();
  }
}
</script>

app/views/payments/index.html.erb
<div class="container mtop">
  <div class="d-flex justify-content-between">
  <h1>Transaction Records</h1>
  <h5>  <%= link_to "Go Back Home", root_path, class: "nav-link backhome" %></h5>
  </div>
  <table>
    <thead>
      <tr class="justify-content-around text-center">
        <th>Title</th>
        <th>Price</th>
        <th>Quantity</th>
      </tr>
    </thead>
    <tbody>
      <% if @orders.present? %>
        <% @orders.each do |order| %>
          <% order.order_items.each do |order_item| %>
            <tr>
              <td><%= order_item.product.title %></td>
              <td><%= order_item.product.price %></td>
              <td><%= order_item.quantity %></td>
            </tr>
          <% end %>
        <% end %>
      <% else %>
        <tr>
          <td colspan="4">No transactions available.</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <%= flash[:success] %>
      </div>
    </div>
  </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const flashMessage = '<%= flash[:success] %>';
    if (flashMessage) {
      $('#successModal').modal('show');
      '<%= flash[:success] = nil %>';
    }
  });
</script>